version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.Dockerfile
        container_name: laravel-php
        volumes:
            - ./src:/var/www/laravel-project
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel-project
        depends_on:
            - php
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        env_file:
            - env/mysql.env
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql_data: