version: '3.8'

services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel-project
        depends_on:
            - php
            - mysql

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel-project
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"  # Changed to standard port
        environment:
            MYSQL_DATABASE: libdb
            MYSQL_USER: libu
            MYSQL_PASSWORD: libp
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - mysql-data:/var/lib/mysql  # Changed to proper MySQL storage

    composer:
        image: composer:latest
        volumes:
            - ./src:/var/www/laravel-project
        working_dir: /var/www/laravel-project

    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel-project
        depends_on:
            - mysql
        entrypoint: ["php", "/var/www/laravel-project/artisan"]

volumes:
    mysql-data: