services:
    # nginx service
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel-project
        depends_on:
            - mysql
            - php
    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel-project
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3346"
        env_file:
            - env/mysql.env
        volumes:
            - ./src:/var/www/laravel-project
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - ./src:/var/www/laravel-project
    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel-project
        entrypoint: ["php", "/var/www/laravel-project/artisan"]
