version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/library-app
    depends_on:
      - mysql
      - php
  php:
    build:
      context: Docker
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/library-app
  composer:
    build:
      context: Docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/library-app
  mysql:
    image: mysql:8.0
    ports:
      - "3336:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./src:/var/www/library-app
  artisan:
    build:
      context: Docker
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/library-app
    entrypoint: ["php", "/var/www/library-app/artisan"]
